const Post = require("../models/postModel")
const Comment = require("../models/commentModel")
const User = require("../models/userModel")
const asyncHandler = require("express-async-handler");
const { body, validationResult } = require("express-validator");
const { trusted } = require("mongoose");
const passport = require("passport");
const bcrypt = require('bcryptjs')
const jwt = require("jsonwebtoken");